name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: WpfApp.sln
      Default_Name: WpfApp
      Project_Name: GI-Artifact-Enhancement-Helper

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Get the current tag version
    - name: Get version from tag
      id: get_version
      run: |
        $ref = "${{ github.ref }}"
        if ($ref -match 'refs/tags/(.*)') {
          $tag = $matches[1]
        } else {
          $tag = "unknown"
        }
        echo "version=$tag" >> $env:GITHUB_OUTPUT

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release /p:Platform="Any CPU"

    # Build the application
    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=Release /p:Platform="Any CPU"

    # List build directory contents to verify the output
    - name: List build directory contents
      run: |
        Get-ChildItem -Recurse -Path "$env:GITHUB_WORKSPACE\bin\Release"
        $exePath = "$env:GITHUB_WORKSPACE\bin\Release\net6.0-windows\$env:Default_Name.exe"
        if (Test-Path $exePath) {
          echo "Executable file found: $exePath"
        } else {
          Write-Error "Executable file not found: $exePath"
        }

    # Rename the build artifacts
    - name: Rename build artifacts
      run: |
        $buildDir = "$env:GITHUB_WORKSPACE\bin\Release\net6.0-windows"
        $outputDir = "$env:GITHUB_WORKSPACE\output"
        
        New-Item -ItemType Directory -Force -Path $outputDir
        
        $exePath = "$buildDir\$env:Default_Name.exe"
        $outputPath = "$outputDir\$env:Project_Name-${{ steps.get_version.outputs.version }}.exe"
        
        Write-Output "Moving from: $exePath"
        Write-Output "Output Dir: $outputDir"
        Write-Output "Moving to: $outputPath"
        
        Move-Item -Path $exePath -Destination $outputPath -Force

    # Create GitHub Release
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    # Upload Release Asset
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}\output\${{ env.Project_Name }}-${{ steps.get_version.outputs.version }}.exe
        asset_name: ${{ env.Project_Name }}-${{ steps.get_version.outputs.version }}.exe
        asset_content_type: application/octet-stream