name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: WpfApp.sln
      Project_Name: WpfApp

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Get the current tag version
    - name: Get version from tag
      id: get_version
      run: |
        $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
        echo "version=$tag" >> $env:GITHUB_OUTPUT

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.8

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release /p:Platform="Any CPU"

    # Build the application
    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=Release /p:Platform="Any CPU"

    # Rename the build artifacts
    - name: Rename build artifacts
      run: |
        $buildDir = "$env:GITHUB_WORKSPACE\bin\Release"
        $outputDir = "$env:GITHUB_WORKSPACE\output"
        New-Item -ItemType Directory -Force -Path $outputDir
        $outputFileName = "$env:Project_Name-${{ steps.get_version.outputs.version }}.exe"
        Move-Item -Path "$buildDir\$env:Project_Name.exe" -Destination "$outputDir\$outputFileName"

    # Upload the build artifacts: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ github.workspace }}\output
